# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-8N2hQUWaOXJXru9wFjZml2dheykUbI
"""
import os
import telebot

TOKEN = os.environ.get('BOT_TOKEN')
bot = telebot.TeleBot(TOKEN)






# ==========================
# إعداد البوت
# ==========================



bot = telebot.TeleBot(TOKEN)


# ==========================
# أسواق الفوركس الحقيقية
# ==========================

MARKETS = {
    "EUR/USD 🇪🇺": "EURUSD",
    "GBP/USD 🇬🇧": "GBPUSD",
    "USD/JPY 🇯🇵": "USDJPY",
    "USD/CHF 🇨🇭": "USDCHF",
    "USD/CAD 🇨🇦": "USDCAD",
    "AUD/USD 🇦🇺": "AUDUSD",
    "NZD/USD 🇳🇿": "NZDUSD",

    "EUR/GBP": "EURGBP",
    "EUR/JPY": "EURJPY",
    "GBP/JPY": "GBPJPY",
    "EUR/CHF": "EURCHF",
    "GBP/CHF": "GBPCHF",

    "AUD/JPY": "AUDJPY",
    "CAD/JPY": "CADJPY",
    "CHF/JPY": "CHFJPY",
    "NZD/JPY": "NZDJPY",

    "AUD/CAD": "AUDCAD",
    "AUD/NZD": "AUDNZD",
    "EUR/AUD": "EURAUD",
    "GBP/AUD": "GBPAUD"
}


# ==========================
# التحليل الفني
# ==========================

def get_analysis(symbol):

    try:

        handler = TA_Handler(
            symbol=symbol,
            screener="forex",
            exchange="OANDA",
            interval=Interval.INTERVAL_1_MINUTE
        )

        analysis = handler.get_analysis()

        result = analysis.summary['RECOMMENDATION']

        if result == "BUY":
            return "🟢 BUY"

        elif result == "SELL":
            return "🔴 SELL"

        else:
            return "⚪ NEUTRAL"

    except Exception as e:
        return "❌ غير متاح حالياً"


# ==========================
# البداية
# ==========================

@bot.message_handler(commands=['start'])
def start(message):

    markup = types.InlineKeyboardMarkup(row_width=2)

    buttons=[]

    for name,code in MARKETS.items():

        buttons.append(
            types.InlineKeyboardButton(
                name,
                callback_data=code
            )
        )

    markup.add(*buttons)

    bot.send_message(
        message.chat.id,
        "🚀 MAD Tr\n\nاختر سوق الفوركس الحقيقي للتحليل:",
        reply_markup=markup
    )



# ==========================
# استقبال الاختيار
# ==========================

@bot.callback_query_handler(func=lambda call: True)
def callback(call):

    pair = call.data

    signal = get_analysis(pair)


    text = f"""
📊 MAD Tr Signal

📈 Pair: {pair}

🎯 Signal: {signal}

⏱ Timeframe: 1 Minute

🌍 Market: Real Forex

⚠️ Execute manually on your platform
"""


    bot.edit_message_text(
        text,
        call.message.chat.id,
        call.message.message_id
    )



print("🚀 MAD Tr Real Forex Bot Running...")

bot.infinity_polling()
